### ISSUE TITLE
QR-Code Generator

### ISSUE THREAD

**Issue by Ysetiowati** [th-koeln/location-based-messages-verwertung#10]
Man kann statisch durch URL verbinden: 

https://www.qrcode-generator.de/

**Comment by janewhat** [comment]
Adresse zu landingpage / Appdownload: http://insahne.com/lbm/index.html

**Comment by Ysetiowati** [comment]
Das QR Code, wo apk drin steht.

![qrcode](https://user-images.githubusercontent.com/22955909/48424800-b8064f80-e763-11e8-96a8-b5c9fdf0e7fe.png)

**Comment by janewhat** [comment]
können wir noch bit.ly Link zur app machen? wenn jemand keinen Scanner hat
