### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by aleksandrashekh** [th-koeln/location-based-messages-verwertung#2]
Erste Version
https://drive.google.com/file/d/1QzlzFj21W-OZ9y65gEodgcCHicMkD5SO/view?usp=sharing

**Comment by janewhat** [comment]
tolles Design! Eventuell müssten wir nochmal doch Beacons mit einbeziehen, damit das klar ist, dass das ortsbasierte Nachrichten sind. Also ein Schaubild wo das verdeutlicht wird

**Comment by janewhat** [comment]
http://insahne.com/lbm/index.html

Texte geändert.

**Comment by aleksandrashekh** [comment]
[index.html.zip](https://github.com/th-koeln/location-based-messages-verwertung/files/2580345/index.html.zip)
Angepasst

**Comment by janewhat** [comment]
[index.html 2.zip](https://github.com/th-koeln/location-based-messages-verwertung/files/2580370/index.html.2.zip)

Überschrift angepasst und texte angepasst

**Comment by janewhat** [comment]
http://insahne.com/lbm/index.html sascha ist LP jetzt ok so ? oder hast du noch was geändert?

**Comment by aleksandrashekh** [comment]
Die finale Version von Landing Page, responsives Verhalten wurde gefixt. 
Es muss nochmal ganzer Ordner heruntergeladen werden, da noch neue Bilder und Styles eingefügt sind.

Teamphoto ist auch dadrin, für Business Design Veranstaltung muss man "display:none" wegnehmen.

https://drive.google.com/file/d/1sWYTAl-iP7k04aah2GckgMU5NA0CAEzO/view?usp=sharing
