### ISSUE TITLE
Werbeartikel erstellen

### ISSUE THREAD

**Issue by janewhat** [th-koeln/location-based-messages-verwertung#6]

**Comment by aleksandrashekh** [comment]
![werbunggross](https://user-images.githubusercontent.com/34030679/48477453-e89cc680-e801-11e8-9a7d-d2f8bd33bab7.jpg)
![werbungklein](https://user-images.githubusercontent.com/34030679/48477454-e89cc680-e801-11e8-990f-607b6ee2a7c5.jpg)
